//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Assets
{
    [Serializable]
    public class HeadMsg : Message
    {
        public const string k_RosMessageName = "Assets/Head";
        public override string RosMessageName => k_RosMessageName;

        public int p;
        public int t;

        public HeadMsg()
        {
            this.p = 0;
            this.t = 0;
        }

        public HeadMsg(int p, int t)
        {
            this.p = p;
            this.t = t;
        }

        public static HeadMsg Deserialize(MessageDeserializer deserializer) => new HeadMsg(deserializer);

        private HeadMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.p);
            deserializer.Read(out this.t);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.p);
            serializer.Write(this.t);
        }

        public override string ToString()
        {
            return "HeadMsg: " +
            "\np: " + p.ToString() +
            "\nt: " + t.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
